### ISSUE TITLE
How can i combine it with clang_complete??

### ISSUE THREAD

**Issue by OsmanthusTree** [othree/vim-autocomplpop#10]
I want to combine vim-autocomplpop with clang_complete 
so that the completion will not be triggered manually any more.

But i just figured out an awkward way: 
add `let let g:acp_behaviorKeywordCommand = "\<C-x>\<C-u>"` to my vimrc

However, if the file i am editing is not c/cpp file, there are lots of errors which show the completefunc is not set ... How can i fix it ?? Thank you ...

**Comment by othree** [comment]
If you can set omnicomplete to use clang_complete
Then everything should just work.
