### ISSUE TITLE
error in function acp#onBs

### ISSUE THREAD

**Issue by primitivorm** [othree/vim-autocomplpop#6]
When I type Backspace, get the following error in Windows:

"Se ha detectado un error al procesar funcion acp#onBs:
Argumentos invalidos para la funcion call: 
  if call(s:behavsCurrent[s:iBehavs].meets, [matchstr(s:getCurrentText(), '.*\ze.')])

I have multi_byte support
I appreciate your help so much!

**Comment by othree** [comment]
Could you try use English language to grab the error messages?
And I might need some sample code.

I have multi_byte support Vim too. Do you have any special function to deal with multi byte character.
Try disable it to see what happens.

**Comment by primitivorm** [comment]
Hello: 

I'm sorry, close this issue my fault was I map \<bs> to other command. 
Deleted this and works correct!

Thanks you
