### ISSUE TITLE
Strange output when entering insert (terminal) mode in Neovim

### ISSUE THREAD

**Issue by sheluchin** [othree/vim-autocomplpop#9]
I don't know if this issue will receive any attention because it's specific to Neovim and not just Vim, but among some 20 plug-ins I'm using in Neovim, this is the only one causing any problem.

Steps to reproduce:
* Open a terminal window in Neovim using `:term`
* Exit terminal mode by pressing `<C-\-n>`
* Enter terminal mode by pressing `i`

![Output]
(http://i.imgur.com/yznTeLf.png)

This does not happen if I disable vim-autocomplpop.

**Comment by ipod825** [comment]
@sheluchin, don't know if you still have the problem. I just fixed the problem.
Just comment the line
```  " nnoremap <silent> i i<C-r>=<SID>feedPopup()<CR>                                                                                   ```
in `autoload/acp.vim` will work.
https://github.com/ipod825/AutoComplPop/commit/022fb17d3ad23160604fadfb4e4cc006099b4add

**Comment by songgao** [comment]
Please see this: https://github.com/neovim/neovim/issues/4494#issuecomment-202141845

Would be nice if the plugin can disable itself for `buftype=terminal`.

**Comment by othree** [comment]
Sorry, very busy now. But I will try to fix this later.

**Comment by glacambre** [comment]
I'm currently using the following:
```
if has("nvim")
    au BufEnter,TermOpen term://* AcpDisable
    au BufLeave term://* AcpEnable
endif
```
It works quite well and doesn't seem to cause too much overhead.

**Comment by othree** [comment]
Thanks @glacambre 
I try add your code snippets into the plugin and it seems to work fine

**Comment by marshallm94** [comment]
Should the above code vim script be put in the acp.vim file? This issue is occurring for me (I see the issue is an old one...)
